var bookConfig = {
   "FlipSound": "Yes",
   "QRCode": "Hide",
   "appLogoIcon": "",
   // "appLogoIcon": "files\/a\/extfile\/logo.png",
   "appLogoLinkURL": "http:\/\/sbicard.com",
   "HomeURL": "",
   "appLogoOpenWindow": "Blank",
   "bookTitle": "Fabindia SBI Card",
   "bookDescription": "",
   "toolbarColor": "#181818",
   "iconColor": "#eeeeee",
   "loadingPicture": "",
   "loadingCaptionColor": "#eeeeee",
   "loadingBackground": "#323232",
   "logoHeight": 25,
   "logoTop": 10,
   "logoPadding": 10,
   "HomeButtonVisible": "Hide",
   "ShareButtonVisible": "Hide",
   "ThumbnailsButtonVisible": "Show",
   "thumbnailAlpha": 70,
   "ZoomButtonVisible": "Show",
   "FullscreenButtonVisible": "Show",
   "TableOfContentButtonVisible": "Show",
   "SearchButtonVisible": "Hide",
   "leastSearchChar": 2,
   "PrintButtonVisible": "Hide",
   "printWatermarkFile": "",
   "BookMarkButtonVisible": "Hide",
   "BackgroundSoundButtonVisible": "Show",
   "BackgroundSoundURL": "./files/music.mp3",
   "BackgroundSoundLoop": -1,
   "HelpButtonVisible": "Hide",
   "helpContentFileURL": "",
   "helpWidth": 400,
   "helpHeight": 450,
   "showHelpContentAtFirst": "No",
   "aboutButtonVisible": "Hide",
   "aboutContactInfoTxt": "",
   "AutoPlayButtonVisible": "Show",
   "autoPlayAutoStart": "No",
   "SlideshowAutoPlay": false,
   "autoPlayDuration": 3,
   "SlideshowPlayInterval": 5,
   "autoPlayLoopCount": "1",
   "minZoomWidth": 403,
   "minZoomHeight": 518,
   "mouseWheelFlip": "Yes",
   "DownloadButtonVisible": "Show",
   "DownloadURL": "./files/download.pdf",
   "UserInforSetting": "",
   "bgBeginColor": "#323232",
   "bgEndColor": "#323232",
   "bgMRotation": 90,
   "backGroundImgURL": "",
   "LeftShadowWidth": 100,
   "LeftShadowAlpha": 1,
   "RightShadowWidth": 40,
   "RightShadowAlpha": 1,
   "pageBackgroundColor": "#FFFFFF",
   "flipshortcutbutton": "Show",
   "OriginPageIndex": 1,
   "RightToLeft": "No",
   "flippingTime": 0.6,
   "retainBookCenter": "Yes",
   "FlipStyle": "Flip",
   "totalPagesCaption": "",
   "pageNumberCaption": "",
   "topMargin": 10,
   "bottomMargin": 10,
   "leftMargin": 10,
   "rightMargin": 10,
   "LinkDownColor": "#0000FF",
   "LinkAlpha": 0.4,
   "OpenWindow": "Blank",
   "googleAnalyticsID": "",
   "UIBaseURL": "",
   "language": "English",
   "AboutAddress": "",
   "AboutAuthor": "NowForm",
   "AboutEmail": "",
   "AboutMobile": "",
   "AboutWebsite": "",
   "AboutDescription": "",
   "totalPageCount": 10,
   "largePageWidth": 504,
   "largePageHeight": 612,
   "normalPath": "files\/large\/",
   "largePath": "files\/large\/",
   "thumbPath": "files\/thumb\/",
   "VideoButtonVisible": "Hide",
   "SlideshowButtonVisible": "Hide",
   "addPaperCoil": "No",
   "AnnotationButtonVisible": "Hide",
   "CompanyLogoFile": "",
   "bleedAreaLeft": "0%",
   "bleedAreaRight": "0%",
   "bleedAreaTop": "0%",
   "bleedAreaBottom": "0%",
   "HardPageEnable": "No",
   "HardInnerPageEnable": "No",
   "borderColor": "#562e0b",
   "BindingType": "side",
   "hardCoverBorderWidth": "8",
   "outerCoverBorder": "Yes",
   "cornerRound": "8",
   "coverTexture": "none",
   "iconFontColor": "#eeeeee",
   "formBackgroundColor": "#181818",
   "formFontColor": "#eeeeee",
   "backgroundOpacity": "100",
   "autoDoublePage": "Yes",
   "searchKeywordFontColor": "#FFB000",
   "backgroundPosition": "Stretch",
   "CurlingPageCorner": "Yes",
   "updatePageURL": "True",
   "isTheBookOpen": "No",
   "FlipDirection": "0",
   "InstructionsButtonVisible": "Hide",
   "showInstructionOnStart": "No",
   "showThicknessOnMobile": "No",
   "highDefinitionConversion": "No",
   "pageNumColor": "#111111",
   "backgroundScene": "None",
   "ShowTopLeftShadow": "Yes",
   "maxWidthToSmallMode": 400,
   "maxHeightToSmallMode": 300,
   "hideMiniFullscreen": "No",
   "isStopMouseMenu": "Yes",
   "haveAdSense": "No",
   "adSenseWidth": 200,
   "adSenseHeight": 200,
   "adSenseLeft": 50,
   "adSenseTop": 50,
   "adSenseClientId": "",
   "SelectTextButtonVisible": "Hide",
   "leftRightPnlShowOption": "none",
   "ToolBarAlpha": "1",
   "enablePageBack": "Hide",
   "CreatedTime": 1594726139,
   "searchTextJS": "files\/search\/book_config.js",
   "searchPositionJS": "files\/search\/text_position[%d].js"
}
var fliphtml5_pages = [
   {
      "l": "files/large/1.jpg",
      "t": "files/thumb/1.jpg"
   },
   {
      "l": "files/large/2.jpg",
      "t": "files/thumb/2.jpg"
   },
   {
      "l": "files/large/3.jpg",
      "t": "files/thumb/3.jpg"
   },
   {
      "l": "files/large/4.jpg",
      "t": "files/thumb/4.jpg"
   },
   {
      "l": "files/large/5.jpg",
      "t": "files/thumb/5.jpg"
   },
   {
      "l": "files/large/6.jpg",
      "t": "files/thumb/6.jpg"
   },
   {
      "l": "files/large/7.jpg",
      "t": "files/thumb/7.jpg"
   },
   {
      "l": "files/large/8.jpg",
      "t": "files/thumb/8.jpg"
   },
   {
      "l": "files/large/9.jpg",
      "t": "files/thumb/9.jpg"
   },
   {
      "l": "files/large/10.jpg",
      "t": "files/thumb/10.jpg"
   }
]
var language = [{ "language": "English", "btnFirstPage": "First", "btnNextPage": "Next", "btnLastPage": "Last", "btnPrePage": "Previous", "btnGoToHome": "Home", "btnDownload": "Download", "btnSoundOn": "Sound On", "btnSoundOff": "Sound Off", "btnPrint": "Print", "btnThumb": "Thumbnails", "btnBookMark": "Bookmark", "frmBookMark": "Bookmark", "btnZoomIn": "Zoom In", "btnZoomOut": "Zoom Out", "btnAutoFlip": "Auto Flip", "btnStopAutoFlip": "Stop Auto Flip", "btnSocialShare": "Share", "btnHelp": "Help", "btnAbout": "About", "btnSearch": "Search", "btnFullscreen": "Fullscreen", "btnExitFullscreen": "Exit Fullscreen", "btnMore": "More", "frmPrintCaption": "Print", "frmPrintall": "Print All Pages", "frmPrintcurrent": "Print Current Page", "frmPrintRange": "Print Range", "frmPrintexample": "Example: 2,3,5-10", "frmPrintbtn": "Print", "frmShareCaption": "Share", "frmShareLabel": "Share", "frmShareInfo": "You can easily share this publication to social networks.Just click the appropriate button below", "frminsertLabel": "Insert to Site", "frminsertInfo": "Use the code below to embed this publication to your website.", "frmaboutcaption": "Contact", "frmaboutcontactinformation": "Contact Information", "frmaboutADDRESS": "Address", "frmaboutEMAIL": "Email", "frmaboutWEBSITE": "Website", "frmaboutMOBILE": "Mobile", "frmaboutAUTHOR": "Author", "frmaboutDESCRIPTION": "Description", "frmSearch": "Search", "frmToc": "Table Of Contents", "btnTableOfContent": "Table Of Contents", "btnNote": "Annotation", "lblLast": "This is the last page.", "lblFirst": "This is the first page.", "lblFullscreen": "Click to view in fullscreen", "lblName": "Name", "lblPassword": "Password", "lblLogin": "Login", "lblCancel": "Cancel", "lblNoName": "User name can not be empty.", "lblNoPassword": "Password can not be empty.", "lblNoCorrectLogin": "Please enter the correct user name and password.", "btnVideo": "Video Gallery", "btnSlideShow": "Slideshow", "pnlSearchInputInvalid": "The search text is too short.", "btnDragToMove": "Move by mouse drag", "btnPositionToMove": "Move by mouse position", "lblHelp1": "Drag the page corner to view", "lblHelp2": "Double click to zoom in, out", "lblCopy": "Copy", "lblAddToPage": "Add To Page", "lblPage": "Page", "lblTitle": "Title", "lblEdit": "Edit", "lblDelete": "Delete", "lblRemoveAll": "Remove All", "tltCursor": "Cursor", "tltAddHighlight": "Add highlight", "tltAddTexts": "Add texts", "tltAddShapes": "Add shapes", "tltAddNotes": "Add notes", "tltAddImageFile": "Add image file", "tltAddSignature": "Add signature", "tltAddLine": "Add line", "tltAddArrow": "Add arrow", "tltAddRect": "Add rect", "tltAddEllipse": "Add ellipse", "lblDoubleClickToZoomIn": "Double click to zoom in.", "lblPages": "Pages", "infCopyToClipboard": "Your browser dose not support clipboard, please do it yourself.", "lblDescription": "Title", "frmLinkLabel": "Link", "infNotSupportHtml5": "HTML5 is not supported by your current web browser, please read the book with latest verson web browser. Here we recommend you to read it with Chrome.", "frmHowToUse": "How To Use", "lblHelpPage1": "Move your finger to flip the book page.", "lblHelpPage2": "Zoom in by using gesture or double click on the page.", "lblHelpPage3": "Click to view the table of content, bookmarks and share your books via social networks.", "lblHelpPage4": "Add bookmarks, use search function and auto flip the book.", "lblHelpPage5": "Open the thumbnails to overview all book pages.", "frmQrcodeCaption": "Scan the bottom two-dimensional code to view with mobile phone.", "btnPageBack": "Backward", "btnPageForward": "Forward", "btnLanguage": "Change Language", "msgConfigMissing": "Configuration file is missing, unable to open the book." }];;
var pageEditor = [];
var ols = [];
var slideshow = [];
var videoList = [];
var bmtConfig = { "tabs": [], "onSideEdge": true };
var staticAd = {};
var flipByAudio = {};
var bookPlugin = null;
var phoneNumber = []; bookConfig.language = "English";